# Generated by Django 4.2.2 on 2023-08-13 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('kanji', models.TextField(max_length=20)),
                ('grade', models.IntegerField(null=True)),
                ('stroke_count', models.IntegerField(null=True)),
                ('frequency', models.IntegerField(null=True)),
                ('jlpt', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('kanji', models.TextField(max_length=1)),
                ('mnemonic', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Onyomi',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('character', models.TextField(max_length=20, null=True)),
                ('kanji_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.kanji')),
            ],
        ),
        migrations.CreateModel(
            name='Meanings',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('character', models.TextField(max_length=100, null=True)),
                ('kanji_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.kanji')),
            ],
        ),
        migrations.CreateModel(
            name='Kunyoumi',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('character', models.TextField(max_length=20, null=True)),
                ('kanji_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.kanji')),
            ],
        ),
    ]
