# Generated by Django 4.2.2 on 2023-07-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unicode', models.IntegerField()),
                ('strokes', models.IntegerField()),
            ],
        ),
    ]
