# Generated by Django 4.2.2 on 2023-08-01 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kanji', models.TextField(max_length=20)),
                ('grade', models.IntegerField(null=True)),
                ('stroke_count', models.IntegerField(null=True)),
                ('frequency', models.IntegerField(null=True)),
                ('jlpt', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Onyomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.TextField(max_length=20, null=True)),
                ('kanji_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kanji')),
            ],
        ),
        migrations.CreateModel(
            name='Meanings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.TextField(max_length=100, null=True)),
                ('kanji_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kanji')),
            ],
        ),
        migrations.CreateModel(
            name='Kunyoumi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.TextField(max_length=20, null=True)),
                ('kanji_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kanji')),
            ],
        ),
    ]
