# Generated by Django 4.2.2 on 2023-08-20 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_rename_username_userinfo_user_id'),
        ('home', '0002_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.userinfo'),
        ),
    ]
